# Generated by Django 3.0 on 2022-05-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chemist_Master', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=30)),
                ('mfg', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('formulation', models.CharField(choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Injection', 'Injection')], max_length=150)),
                ('chemist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Chemist_Master.ChemistRegister')),
            ],
        ),
    ]
