# Generated by Django 3.0 on 2022-05-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30, null='False', verbose_name='Medicine_Name')),
                ('symptoms', models.CharField(max_length=1000, null='False')),
                ('diseases', models.CharField(max_length=1000, null='False')),
                ('category', models.CharField(max_length=50, null='False', verbose_name='Type')),
                ('unit', models.CharField(max_length=10, null='False', verbose_name='Unit')),
                ('unit_price', models.FloatField(null='False', verbose_name='Unit_price')),
                ('package_unit', models.CharField(max_length=10, null='False', verbose_name='Package_Unit')),
                ('package_price', models.FloatField(null='False', verbose_name='Package_price')),
                ('drug', models.CharField(max_length=20, null='False', verbose_name='Drug_Name')),
                ('per_unit', models.CharField(max_length=10, null='False', verbose_name='per_unit')),
                ('indication', models.CharField(max_length=100, verbose_name='Indication')),
                ('contraindication', models.CharField(max_length=100, verbose_name='Containdication')),
                ('caution', models.CharField(max_length=500, null='True', verbose_name='Caution')),
                ('side_effect', models.CharField(max_length=500, null='True', verbose_name='Side-Effect')),
            ],
        ),
    ]
