# Generated by Django 3.0 on 2022-05-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.EmailField(max_length=50, verbose_name='Email')),
                ('chemistpwd', models.CharField(max_length=20, verbose_name='Password')),
                ('chemistfname', models.CharField(default='', max_length=20, verbose_name='First_Name')),
                ('chemistmname', models.CharField(default='', max_length=20, verbose_name='Middle_Name')),
                ('chemistlname', models.CharField(default='', max_length=20, verbose_name='Last_Name')),
                ('chemistaddress', models.CharField(default='', max_length=20, verbose_name='Address')),
                ('chemistcity', models.CharField(default='', max_length=20, verbose_name='City')),
                ('chemistarea', models.CharField(default='', max_length=20, verbose_name='Area')),
                ('chemistpincode', models.IntegerField(default='', verbose_name='Pincode')),
                ('chemistcontactno', models.IntegerField(default='', verbose_name='Contact_No')),
                ('chemistphoto', models.FileField(upload_to='upload', verbose_name='store certificate')),
                ('forgot_pass', models.CharField(default='', max_length=100, verbose_name='Write your password hint')),
            ],
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(blank=True, max_length=50)),
                ('PersonName', models.CharField(blank=True, max_length=50)),
                ('Contact', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('password', models.CharField(max_length=50)),
                ('add1', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SK_Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_No', models.CharField(default='', max_length=200)),
                ('pd_nm', models.CharField(default='', max_length=200)),
                ('pd_price', models.FloatField(default=0.0)),
                ('pd_qty', models.IntegerField(default=0)),
                ('pd_tot', models.FloatField(default=0.0)),
                ('date_data', models.DateField(blank=True, null=True)),
                ('store_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Chemist_Master.ChemistRegister')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=50)),
                ('productquantity', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('isDeny', models.BooleanField(default=False)),
                ('Bills_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('store_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Chemist_Master.ChemistRegister')),
            ],
        ),
    ]
