# Generated by Django 3.0 on 2022-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chemist_Master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistregister',
            name='chemistphoto',
            field=models.FileField(blank=True, null=True, upload_to='upload', verbose_name='store certificate'),
        ),
    ]
