# Generated by Django 3.0 on 2022-05-16 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.EmailField(max_length=50, unique='True', verbose_name='Email')),
                ('userpwd', models.CharField(max_length=20, verbose_name='Password')),
                ('userfname', models.CharField(default='', max_length=20, verbose_name='First_Name')),
                ('usermname', models.CharField(default='', max_length=20, verbose_name='Middle_Name')),
                ('userlname', models.CharField(default='', max_length=20, verbose_name='Last_Name')),
                ('useraddress', models.CharField(default='', max_length=20, verbose_name='Address')),
                ('usercity', models.CharField(default='', max_length=30, verbose_name='City')),
                ('userarea', models.CharField(default='', max_length=20, verbose_name='Area')),
                ('userpincode', models.IntegerField(default='', verbose_name='Pincode')),
                ('usercontactno', models.IntegerField(default='', verbose_name='Contact_No')),
                ('forgot_pass', models.CharField(default='', max_length=100, verbose_name='Write your password hint')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guides')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Master.UserRegister')),
            ],
        ),
    ]
